using System;
using System.Diagnostics;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading;

namespace IronIdGenerator;

[Generator]
public sealed class IronIdGenerator : IIncrementalGenerator
{
    private const string GeneratedCodeAttribute = $"""[global::System.CodeDom.Compiler.GeneratedCodeAttribute("IronIdGenerator.IronIdGenerator", "{Version.Current}")]""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // context.RegisterPostInitializationOutput(ctx => ctx.AddSource($"{GeneratedCodeNamespace}.g.cs", CommonSrc));

        // Then generate individual ID types
        var syntaxProvider = context.SyntaxProvider
            .CreateSyntaxProvider(SyntacticPredicate, SemanticTransform)
            .Where(static type => type is not null)
            .Select(EntityIronIdContext.FromEntityTypeInfo!)
            .WithComparer(PartialClassContextEqualityComparer.Instance);

        context.RegisterSourceOutput(syntaxProvider, Execute);
    }

    private static bool SyntacticPredicate(SyntaxNode node, CancellationToken _) => node switch
    {
        ClassDeclarationSyntax { AttributeLists.Count: > 0 } classDeclarationSyntax =>
            classDeclarationSyntax.AttributeLists.Any(static attr => attr.Attributes.Any(static a => a.Name.ToString() == "IronId")),
        RecordDeclarationSyntax { AttributeLists.Count: > 0 } recordDeclarationSyntax =>
            recordDeclarationSyntax.AttributeLists.Any(static attr => attr.Attributes.Any(static a => a.Name.ToString() == "IronId")),
        _ => false,
    };

    private static INamedTypeSymbol? SemanticTransform(GeneratorSyntaxContext context, CancellationToken ct)
    {
        Debug.Assert(context.Node is ClassDeclarationSyntax or RecordDeclarationSyntax);

        TypeDeclarationSyntax candidate = context.Node switch
        {
            ClassDeclarationSyntax => Unsafe.As<ClassDeclarationSyntax>(context.Node),
            RecordDeclarationSyntax => Unsafe.As<RecordDeclarationSyntax>(context.Node),
            _ => throw new Exception("IronIdAttribute found on something that is neither a record or a class"),
        };

        if (context.SemanticModel.GetDeclaredSymbol(candidate, ct) is { } entityType)
        {
            var ironId = context.SemanticModel.Compilation.GetTypeByMetadataName("System.IronIdAttribute");
            if (ironId is not null)
                return entityType as INamedTypeSymbol;
        }

        return null;
    }
    
    private static void Execute(SourceProductionContext context, EntityIronIdContext subject)
    {
        var idClassName = $"{subject.TypeName}Id";
        var converterClassName = $"{idClassName}JsonConverter";

        // Handle namespace - if it's empty, use global namespace declaration
        var namespaceDeclaration = string.IsNullOrEmpty(subject.Namespace)
            ? ""
            : $"namespace {subject.Namespace};";

        var idSource = $$"""
                         // <auto-generated/>
                         #pragma warning disable
                         #nullable enable

                         {{namespaceDeclaration}}

                         /// <summary>
                         /// Represents a {{idClassName}} Iron ID type. Uses prefix "{{subject.Prefix}}".
                         /// To create a new instance, use {{idClassName}}.New().
                         /// </summary>
                         /// <param name="Value">The Ulid value from which to construct this Id</param>
                         {{GeneratedCodeAttribute}}
                         [global::System.Text.Json.Serialization.JsonConverter(typeof({{converterClassName}}))]
                         [global::System.ComponentModel.TypeConverter(typeof({{idClassName}}TypeConverter))]
                         public readonly record struct {{idClassName}}(global::System.Ulid Value) : global::System.IIronId, global::System.IComparable, global::System.IParsable<{{idClassName}}>
                         {
                             public const string Prefix = "{{subject.Prefix}}";
                             
                             public static readonly {{idClassName}} Empty = new(global::System.Ulid.Empty);
                             public static {{idClassName}} New() => new(global::System.Ulid.NewUlid());

                             public {{idClassName}}() : this(global::System.Ulid.NewUlid()) {}
                             
                             public override string ToString() => $"{Prefix}_{Value}".ToLower();
                             
                             /// <summary>
                             /// Gets the underlying Ulid value. Implements IIronId.GetValue().
                             /// </summary>
                             public global::System.Ulid GetValue() => Value;
                             public static {{idClassName}} Parse(string s, global::System.IFormatProvider? provider = default) => TryParse(s, provider, out var result) ? result : throw new global::System.FormatException();
                             public static bool TryParse([global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] string? s, global::System.IFormatProvider? provider, out {{idClassName}} result)
                             {
                                 result = default!;

                                 if (!string.IsNullOrWhiteSpace(s)
                                     && s.Split("_") is [.. var typeNameParts, var idValue]
                                     && string.Join('_', typeNameParts) is var typeName 
                                     && typeName.Equals(Prefix, global::System.StringComparison.OrdinalIgnoreCase)
                                     && global::System.Ulid.TryParse(idValue.ToUpperInvariant(), out var id))
                                 {
                                     result = new {{idClassName}}(id);
                                     return true;
                                 }

                                 return false;
                             }
                             
                             public static implicit operator string({{idClassName}} id) => id.ToString();
                             public static explicit operator {{idClassName}}(string id) => Parse(id);
                             
                             public static implicit operator global::System.Ulid({{idClassName}} id) => id.Value;
                             public static explicit operator {{idClassName}}(global::System.Ulid id) => new {{idClassName}}(id);
                             
                             public int CompareTo(object value)
                             {
                                 if (value == null) return 1;
                                 if (value is {{idClassName}} other) return this.Value.CompareTo(other.Value);
                                 throw new global::System.ArgumentException("Object must be of type {{idClassName}}.", nameof(value));
                             }
                         }

                         /// <summary>
                         /// System.Text.Json converter for {{idClassName}}.
                         /// </summary>
                         {{GeneratedCodeAttribute}}
                         public sealed class {{converterClassName}} : global::System.Text.Json.Serialization.JsonConverter<{{idClassName}}>
                         {
                             public override {{idClassName}} Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
                             {
                                 var value = reader.GetString();
                                 if (value is null)
                                     throw new global::System.Text.Json.JsonException($"Cannot deserialize null to {{idClassName}}.");
                                 
                                 if (!{{idClassName}}.TryParse(value, null, out var result))
                                     throw new global::System.Text.Json.JsonException($"Invalid {{idClassName}} format: {value}");
                                 
                                 return result;
                             }

                             public override void Write(global::System.Text.Json.Utf8JsonWriter writer, {{idClassName}} value, global::System.Text.Json.JsonSerializerOptions options)
                             {
                                 writer.WriteStringValue(value.ToString());
                             }
                         }


                         /// <summary>
                         /// System.ComponentModel.TypeConverter for {{idClassName}}.
                         /// Enables type conversion for ASP.NET Core model binding and other framework scenarios.
                         /// </summary>
                         {{GeneratedCodeAttribute}}
                         public sealed class {{idClassName}}TypeConverter : global::System.ComponentModel.TypeConverter
                         {
                             public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType) =>
                                 sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);

                             public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value) =>
                                 value is string str && {{idClassName}}.TryParse(str, culture, out var id) ? id : base.ConvertFrom(context, culture, value);

                             public override bool CanConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type? destinationType) =>
                                 destinationType == typeof(string) || base.CanConvertTo(context, destinationType);

                             public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType) =>
                                 destinationType == typeof(string) && value is {{idClassName}} id ? id.ToString() : base.ConvertTo(context, culture, value, destinationType);
                         }
                         """;

        context.AddSource($"IronId.Generated.{idClassName}.g.cs", idSource);
    }
}
